### ISSUE TITLE
organizer involvement in events

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#11]
reminder: be sure that the manuscript discusses how deeply the organizers (typically) are involved as participant-leaders during the actual event.  Possibly it is important that most of the organizers attend as participants and offer pitches.  More importantly, we honestly do not know (at least, I don't) what would happen at a hackathon if (for instance) only 2 organizers came and they acted purely as facilitators rather than getting into the mix and proposing pitches and helping to lead teams.

**Comment by msrosenberg** [comment]
This is interesting because at some point during our meeting, someone suggested that one way to make participants to feel welcome (and to give them a sense of ownership) was to make sure that the pitching/etc. was not dominated by the LT and I thought someone had even suggesting not allowing LT to pitch. Maybe its a balancing act?

Does anyone have a feel for whether an active LT at the hackathon is a plus or minus or just depends on the circumstances?

**Comment by epontell** [comment]
On the other hand, pitches by the LT have been a good instrument to keep the
focus on the set scope. I think we had pitches from LT members very often in
hackathons.

Enrico

From:  Michael Rosenberg notifications@github.com
Reply-To:  arlin/hip_hack_howto
<reply+0014c328faf5379673686387b65945657f2a7b55d72e82b892cf00000001111f1ddd9
2a169ce03b427d9@reply.github.com>
Date:  Monday, March 16, 2015 at 4:40 PM
To:  arlin/hip_hack_howto hip_hack_howto@noreply.github.com
Subject:  Re: [hip_hack_howto] organizer involvement in events (#11)

This is interesting because at some point during our meeting, someone
suggested that one way to make participants to feel welcome (and to give
them a sense of ownership) was to make sure that the pitching/etc. was not
dominated by the LT and I thought someone had even suggesting not allowing
LT to pitch. Maybe its a balancing act?

Does anyone have a feel for whether an active LT at the hackathon is a plus
or minus or just depends on the circumstances?

‹
Reply to this email directly or view it on GitHub
https://github.com/arlin/hip_hack_howto/issues/11#issuecomment-81970262 .

**Comment by hlapp** [comment]
On 3/16/15, 6:40 PM, Michael Rosenberg wrote:

> Does anyone have a feel for whether an active LT at the hackathon is a
> plus or minus or just depends on the circumstances?

I think it can go both ways and depends on the hackathon. I want to
think that on average it doesn't matter, but of course we lack data to
conclude one way or the other. The R PopGen hackathon is turning out to
be a data point with only one project pitch from a co-organizer.

There is a temptation to consider everything we did in deliberate
fashion as having had a (presumably positive) effect. But for some of
even the things we did with great thoughtfulness, the hackathons may
have just turned out as well without them. I'm not sure how we would
know one way or the other.

## 

Hilmar Lapp -:- lappland.io

**Comment by epontell** [comment]
I tend to agree with Hilmar, I am not sure that pitches from LT members was always a deliberate aspect of the hackathon organization, but perhaps more of a side effect of how vested and committed were the members of the LT. In retrospect, it does help in keeping the event focused.

**Comment by rvosa** [comment]
This issue is kind of the same (but less data-centric) than the following one in the data repo: https://github.com/NESCent/hackathon_data/issues/1 - it seems to me that it is going to be pretty hard to reconstruct who pitched what at which event, and it's also not going to be very informative. I'm leaving this issue and the one on the data repo open for now, though my inclination would be to close this.

**Comment by rvosa** [comment]
My inclination to close this is growing. Perhaps we simply need to remember to address this in #67 and elsewhere.

**Comment by arlin** [comment]
I'm going to label this wontfix.  we are already saying too much.  we need to be choosier so that the reader doesn't fall asleep before we get the main points across.
