### ISSUE TITLE
graphic illustrating diversity outcomes

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#16]
Apparently we have data to show an increase in diversity. I'd like to see a graphic showing diversity as a function of time (event date). This could combine women and minorities, or separate them out.

**Comment by epontell** [comment]
I have added some preliminary graphics in the hackathon_data repository. Three charts, one compares numbers of women and minorities to participants; the other two summarize % of each group.

**Comment by arlin** [comment]
excellent!  what happened with event 5 (GMOD tools)?  maybe there is a lesson there about how not to do things?

**Comment by arlin** [comment]
The low diversity at this event could be an extreme random deviate (bad luck), but is also can serve to illustrate one of our lessons learned.  The organizing team for event 5 was 1/6 XX and 5/6 XY, which is not unusual.  The open call (http://gmod.org/wiki/GMOD_Evo_Hackathon_Open_Call) did not specifically encourage women & minorities to apply.  The open call mentions non-programmer roles but they are all "power user", "guru", "expert" and "wizard", which is language that we decided later was going to be off-putting to prospective XX applicants who tend to undervalue their mad skilz.  Hilmar, do you know if the organizing team took steps to identify prospective women & minority participants and urge them to apply? 

I'll put something about this in the manuscript.  Feel free to comment or revise it there.

**Comment by hlapp** [comment]
> Hilmar, do you know if the organizing team took steps to identify prospective women & minority participants and urge them to apply?

I can't remember that this was done. (I think we only truly started to do this after this event.) I also just checked the applicant pool for this event, and it was highly impoverished in diversity. A high fraction of the applicants from underrepresented groups _was_ admitted, reinforcing the notion that once your applicant pool lacks diversity, it is very difficult or impossible to achieve a diverse participant group.

What should not be overlooked here is that fields bring their own diversity and gender issues to the starting line, and that different fields can differ a lot in this regard. For example, software engineering-heavy fields tend to bring a strong lack of diversity among practitioners, whereas fields heavy on mathematics, statistics, and algorithmics do much less so. For example, many of the applicants to event 9 (which had a diverse applicant pool) from otherwise underrepresented groups were unknown to the organizing group, i.e., applied not because someone from the organizing group had reached out to them.

**Comment by hlapp** [comment]
BTW you might also note that the most lasting products from event 5 (the Nat Div Chado module and paper) were from the (only) diverse group.

**Comment by arlin** [comment]
closing this.  We might want to tweak this a bit, but Enrico made the graphics and put them in https://github.com/NESCent/hackathon_data/blob/master/Graphics.  I put a link in the manuscript at the appropriate spot
