### ISSUE TITLE
re-do the Web-o-Sci search

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#30]
the current draft refers to this result: "a Web of Science search for "hackathon", "hackfest", and "codefest" reveals only 11 papers through 2014 (one each from 2007, 2012, and 2013, with the remaining eight from 2014)."   

Run this search again and update the numbers.

**Comment by arlin** [comment]
OK, Mike, thanks for taking this.

**Comment by msrosenberg** [comment]
I redid this search and found the exact same thing. On Web of Science, a search for "hackathon" or "hackfest" or "codefest" (all three, just like that), reveals exactly 11 papers up through 2014 (and only 3 of those are pre-2014). If there are papers that others think should be there are missing, it is either because (a) none of those words are in the title/abstract/extended keywords (making them unfindable through those terms), or (b) the paper is published in an outlet not covered by WoS (e.g., obscure journals or conference proceedings). 

If one wants to view this as a failure of WoS that's fine, but it's still noteworthy that one of the biggest scientific literature search engines finds almost no literature on the topic prior to 2014.

Speaking of which, there are six additional results for 2015, meaning that with 8 last year and 6 (so far) this year, over 80% of the papers published in WoS on hackathons are from the last two years. 

For those who are curious, here are all 17:

Almirall, E., M. Lee, and A. Majchrzak. 2014. Open innovation requires integrated competition-community ecosystems: Lessons learned from civic open innovation. Business Horizons 57:391-400.

Aungst, T. D. 2015. Using a Hackathon for Interprofessional Health Education Opportunities. Journal of Medical Systems 39.

Barau, A. S., and N. Al Hosani. 2015. Prospects of environmental governance in addressing sustainability challenges of seawater desalination industry in the Arabian Gulf. Environmental Science & Policy 50:145-154.

Bond, R. R., M. D. Mulyenna, D. D. Finlay, and S. Martin. 2015. Multi-faceted informatics system for digitising and streamlining the reablement care model. Journal of Biomedical Informatics 56:30-41.

Curtis, V. 2014. Public Engagement Through the Development of Science-Based Computer Games: The Wellcome Trust's "Gamify Your PhD" Initiative. Science Communication 36:379-387.

Davies, N., D. Field, L. Amaral-Zettler, K. Barker, M. Bicak, S. Bourlat, J. Coddington, J. Deck, A. Drummond, J. A. Gilbert, F. O. Gloeckner, R. Kottmann, C. Meyer, N. Morrison, M. Obst, R. Robbins, L. Schriml, P. Sterk, and S. Stones-Havas. 2014. Report of the 14(th) Genomic Standards Consortium Meeting, Oxford, UK, September 17-21, 2012. Standards in Genomic Sciences 9.

DePasse, J. W., A. Yost, R. Carroll, D. Santorino, A. Ippolito, Z. Chu, and K. R. Olson. 2014. LESS NOISE, MORE HACKING: HOW TO DEPLOY PRINCIPLES FROM MIT'S HACKING MEDICINE TO ACCELERATE HEALTH CARE. International Journal of Technology Assessment in Health Care 30:260-264.

Fafalios, P., and P. Papadakos. 2014. Theophrastus: On demand and real-time automatic annotation and exploration of (web) documents using open linked data. Journal of Web Semantics 29:31-38.

Groen, D., and B. Calderhead. 2015. Science hackathons for developing interdisciplinary research and collaborations. Elife 4.

Irani, L. 2015. Hackathons and the Making of Entrepreneurial Citizenship. Science Technology & Human Values 40:799-824.

Johnson, P., and P. Robinson. 2014. Civic Hackathons: Innovation, Procurement, or Civic Engagement? Review of Policy Research 31:349-357.

Lapp, H., S. Bala, J. P. Balhoff, A. Bouck, N. Goto, M. Holder, R. Holland, A. Holloway, T. Katayama, P. O. Lewis, A. J. Mackey, B. I. Osborne, W. H. Piel, S. L. K. Pond, A. F. Y. Poon, W.-G. Qiu, J. E. Stajich, A. Stoltzfus, T. Thierer, A. J. Vilella, R. A. Vos, C. M. Zmasek, D. J. Zwickl, and T. J. Vision. 2007. The 2006 NESCent Phyloinformatics Hackathon: A Field Report. Evolutionary Bioinformatics 3:287-296.

McCarty, N. A., R. Geyer, T. Allen, A. Gardner, J. Carter, R. Bandyopadhyay, M. Flanigan, P. Walker, S. Walker, S. Henderson, E. Klementich, S. Matthews, and M. L. Maliniak. 2014. HACK FOR CF, THE CYSTIC FIBROSIS HACKATHON. Pediatric Pulmonology 49:391-391.

Mulholland, G., and B. Meredig. 2015. Hackathon aims to solve materials problems. Mrs Bulletin 40:366-367.

Stoltzfus, A., H. Lapp, N. Matasci, H. Deus, B. Sidlauskas, C. M. Zmasek, G. Vaidya, E. Pontelli, K. Cranston, R. Vos, C. O. Webb, L. J. Harmon, M. Pirrung, B. O'Meara, M. W. Pennell, S. Mirarab, M. S. Rosenberg, J. P. Balhoff, H. M. Bik, T. A. Heath, P. E. Midford, J. W. Brown, E. J. McTavish, J. Sukumaran, M. Westneat, M. E. Alfaro, A. Steele, and G. Jordan. 2013. Phylotastic! Making tree-of-life knowledge accessible, reusable and convenient. BMC Bioinformatics 14.

Tuama, E. O., J. Deck, G. Droege, M. Doring, D. Field, R. Kottmann, J. Ma, H. Mori, N. Morrison, P. Sterk, H. Sugawara, J. Wieczorek, L. Wu, and P. Yilmaz. 2012. Meeting Report: Hackathon-Workshop on Darwin Core and MIxS Standards Alignment (February 2012). Standards in Genomic Sciences 7:166-170.

Wieczorek, J., O. Banki, S. Blum, J. Deck, M. Doring, G. Droege, D. Endresen, P. Goldstein, P. Leary, L. Krishtalka, E. O. Tuama, R. J. Robbins, T. Robertson, and P. Yilmaz. 2014. Meeting Report: GBIF hackathon-workshop on Darwin Core and sample data (22-24 May 2013). Standards in Genomic Sciences 9:614-627.

**Comment by arlin** [comment]
while trying to get some of these into my endnote library, I noticed another one on PubMed that is not on Web-o-Sci, which apparently doesn't index Biology Direct: 

  http://www.ncbi.nlm.nih.gov/pubmed/26282399

**Comment by msrosenberg** [comment]
So I checked and that article is in Web of Science. This made me take a closer look and I figured out the problem. Pluralization! That article comes up if we search for "hackathons" but not "hackathon". I never realized Web of Science's search was that limited/specific.

Redoing the search to include plural versions of the three search terms added six more references (shown below), one from 2012, one from 2013, two from 2014, and two from 2015. 

Aitamurto, T., and S. C. Lewis. 2013. Open innovation in digital journalism: Examining the impact of Open APIs at four news organizations. New Media & Society 15:314-331.

Costanza-Chock, S. 2012. Mic Check! Media Cultures and the Occupy Movement. Social Movement Studies 11:375-385.

Komssi, M., D. Pichlis, M. Raatikainen, K. Kindstrtm, and J. Jaervinen. 2015. What Are Hackathons For? Ieee Software 32:60-67.

Milojicic, D. S. 2014. Reinventing Relevance. Computer 47:6-8.

Moeller, S., E. Afgan, M. Banck, R. J. P. Bonnal, T. Booth, J. Chilton, P. J. A. Cock, M. Gumbel, N. Harris, R. Holland, M. Kalas, L. Kajan, E. Kibukawa, D. R. Powel, P. Prins, J. Quinn, O. Sallou, F. Strozzi, T. Seemann, C. Sloggett, S. Soiland-Reyes, W. Spooner, S. Steinbiss, A. Tille, A. J. Travis, R. V. Guimera, T. Katayama, and B. A. Chapman. 2014. Community-driven development for computational biology at Sprints, Hackathons and Codefests. BMC Bioinformatics 15.

Spjuth, O., E. Bongcam-Rudloff, G. C. Hernandez, L. Forer, M. Giovacchini, R. V. Guimera, A. Kallio, E. Korpelainen, M. M. Kandula, M. Krachunov, D. P. Kreil, O. Kulev, P. P. Labaj, S. Lampa, L. Pireddu, S. Schonherr, A. Siretskiy, and D. Vassilev. 2015. Experiences with workflows for automating data-intensive bioinformatics. Biology Direct 10.

**Comment by arlin** [comment]
We had the last 2 already.  I got citation information for the first 4 and put that in EndNote.

Then I made a bullet list with all the papers that match “hackathon”, and I put that in the references section of the paper.

Then I merged this with the old list so that it includes Aidan’s notes in the manuscript.

Arlin

On Oct 16, 2015, at 1:51 PM, Michael Rosenberg <notifications@github.com<mailto:notifications@github.com>> wrote:

So I checked and that article is in Web of Science. This made me take a closer look and I figured out the problem. Pluralization! That article comes up if we search for "hackathons" but not "hackathon". I never realized Web of Science's search was that limited/specific.

Redoing the search to include plural versions of the three search terms added six more references (shown below), one from 2012, one from 2013, two from 2014, and two from 2015.

Aitamurto, T., and S. C. Lewis. 2013. Open innovation in digital journalism: Examining the impact of Open APIs at four news organizations. New Media & Society 15:314-331.

Costanza-Chock, S. 2012. Mic Check! Media Cultures and the Occupy Movement. Social Movement Studies 11:375-385.

Komssi, M., D. Pichlis, M. Raatikainen, K. Kindstrtm, and J. Jaervinen. 2015. What Are Hackathons For? Ieee Software 32:60-67.

Milojicic, D. S. 2014. Reinventing Relevance. Computer 47:6-8.

Moeller, S., E. Afgan, M. Banck, R. J. P. Bonnal, T. Booth, J. Chilton, P. J. A. Cock, M. Gumbel, N. Harris, R. Holland, M. Kalas, L. Kajan, E. Kibukawa, D. R. Powel, P. Prins, J. Quinn, O. Sallou, F. Strozzi, T. Seemann, C. Sloggett, S. Soiland-Reyes, W. Spooner, S. Steinbiss, A. Tille, A. J. Travis, R. V. Guimera, T. Katayama, and B. A. Chapman. 2014. Community-driven development for computational biology at Sprints, Hackathons and Codefests. BMC Bioinformatics 15.

Spjuth, O., E. Bongcam-Rudloff, G. C. Hernandez, L. Forer, M. Giovacchini, R. V. Guimera, A. Kallio, E. Korpelainen, M. M. Kandula, M. Krachunov, D. P. Kreil, O. Kulev, P. P. Labaj, S. Lampa, L. Pireddu, S. Schonherr, A. Siretskiy, and D. Vassilev. 2015. Experiences with workflows for automating data-intensive bioinformatics. Biology Direct 10.

—
Reply to this email directly or view it on GitHubhttps://github.com/arlin/hip_hack_howto/issues/30#issuecomment-148784508.

---

Arlin Stoltzfus (arlin@umd.edumailto:arlin@umd.edu)
Research Biologist, NIST; Fellow, IBBR; Adj. Assoc. Prof., UMCP
IBBR, 9600 Gudelsky Drive, Rockville, MD, 20850
tel: 240 314 6208; web: www.molevol.orghttp://www.molevol.org

**Comment by rvosa** [comment]
If we care about this then it's worth noting that google scholar throws up
a few more results, e.g. (unpublished) grey literature and such.

Op Fri, 16 Oct 2015 om 20:42 schreef Arlin Stoltzfus <
notifications@github.com>

> We had the last 2 already. I got citation information for the first 4 and
> put that in EndNote.
> 
> Then I made a bullet list with all the papers that match “hackathon”, and
> I put that in the references section of the paper.
> 
> Then I merged this with the old list so that it includes Aidan’s notes in
> the manuscript.
> 
> Arlin
> 
> On Oct 16, 2015, at 1:51 PM, Michael Rosenberg <notifications@github.com
