### ISSUE TITLE
revive lost wiki content

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#63]
URLs like this do not work anymore: 

http://www.evoio.org/wiki/Phyloreferencing_subgroup

**Comment by hlapp** [comment]
Is someone working on reviving this already?

**Comment by rvosa** [comment]
@hlapp, it sounds like you are, thanks so much! Will you close this ticket when you're ready to?

**Comment by arlin** [comment]
I'd like to close this and start a separate ticket for us to test the links.  i will provide a list of where to look for EvoIO links.

**Comment by hlapp** [comment]
> I'd like to close this and start a separate ticket for us to test the links.

For reference, I assume this separate ticket is #76. The EvoInfo, Phyloinformatics, and EvoIO wikis are now all back up, and URLs should resolve so long as they are in canonical wiki page form (i.e., do not have index.php in the URL, and use the evoinfo.nescent.org and informatics.nescent.org domains, rather than the `www.nescent.org/wg_{evoinfo,phyloinformatics}` forms).
